name: auto tag

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Update Version
        run: npm version patch
      - name: Push Changes
        run: |
          git push
          git push --tags
          git commit -m "ci: auto update version by github-actions[bot]"
